#!/usr/bin/env bash

nxInstall() {
    nxPrint "Installing Adapta GTK theme..."

    sudo add-apt-repository ppa:tista/adapta -y
    sudo apt update

    sudo apt install adapta-gtk-theme fonts-noto fonts-roboto -y

    gsettings set org.gnome.desktop.interface gtk-theme Adapta-Eta
    gsettings set org.gnome.shell.extensions.user-theme name Adapta-Eta

    gsettings set org.gnome.desktop.interface document-font-name "Roboto 10"
    gsettings set org.gnome.desktop.interface font-name "Noto Sans 10"
    gsettings set org.gnome.desktop.interface monospace-font-name "Ubuntu Mono 10"
    gsettings set org.gnome.desktop.wm.preferences titlebar-font "Noto Sans Bold 10"
}
