#!/usr/bin/env bash

nxInstall() {
    nxPrint "Installing Adapta GTK theme..."

    sudo add-apt-repository -y ppa:tista/adapta
    sudo apt update

    sudo apt-get install -qqy adapta-gtk-theme

    gsettings set org.gnome.desktop.interface gtk-theme Adapta-Eta
    gsettings set org.gnome.shell.extensions.user-theme name Adapta-Eta
}
