#!/usr/bin/env bash

nxConfig() {
    nxConfirm telegram "Install Telegram?" yes
}

nxInstall() {
    if ! $(nxConfirm telegram); then
        return
    fi

    nxPrint "Installing Telegram..."

    wget -P /tmp --trust-server-names -q https://telegram.org/dl/desktop/linux
    tar -xf /tmp/tsetup.*.tar.xz
    sudo mv Telegram /opt/

    mkdir -p ~/.local/share/applications
    cp telegramdesktop.desktop ~/.local/share/applications/
}
