#!/usr/bin/env bash

nxConfig() {
    nxConfirm plex-media-server "Install Plex Media Server?" yes
    nxConfirm plex-media-server-config "Configure Plex Media Server?" yes
}

nxInstall() {
    if ! $(nxConfirm plex-media-server); then
        return
    fi

    nxPrint "Installing Plex Media Server..."
    nxPrint "  NOTE: Service disabled by default."

    sudo apt-get -qqy install jq

    local deb=$(wget -qO - https://plex.tv/api/downloads/1.json | jq -r '.computer.Linux.releases[] | select( .build == "linux-ubuntu-x86_64") | .url' | head -1)

    wget -P /tmp -q $deb
    sudo apt-get -qqy install /tmp/plexmediaserver_*_amd64.deb
    sudo systemctl -q disable plexmediaserver

    if $(nxConfirm plex-media-server-config); then
        nxPrint "Installing Plex Media Server config..."

        sudo mkdir -p /var/lib/plexmediaserver/Library/Movies
        sudo mkdir -p /var/lib/plexmediaserver/Library/TV\ Shows/
        sudo chown -R $USER:$USER /var/lib/plexmediaserver/Library/Movies
        sudo chown -R $USER:$USER /var/lib/plexmediaserver/Library/TV\ Shows/
    fi
}
