#!/usr/bin/env bash

nxConfig() {
    nxConfirm remove-firefox "Remove Firefox?" yes
}

nxInstall() {
    if ! $(nxConfirm remove-firefox); then
        return
    fi

    nxPrint "Removing Firefox..."
    sudo apt-get -qqy purge firefox
}
