#!/usr/bin/env bash

nxInstall() {
    nxPrint "Installing Capitaine cursors..."

    local repo="https://github.com/keeferrourke/capitaine-cursors.git"
    local path="/tmp/capitaine-cursors"

    git clone -q $repo $path
    sudo cp -pr $path/bin/xcursor /usr/share/icons/capitaine-cursors

    gsettings set org.gnome.desktop.interface cursor-theme "Capitaine-cursors"
}
