#!/usr/bin/env bash

nxInstall() {
    nxPrint "Installing Capitaine cursors..."

    git clone https://github.com/keeferrourke/capitaine-cursors.git
    sudo cp -pr capitaine-cursors/bin/xcursor /usr/share/icons/capitaine-cursors
    rm -rf capitaine-cursors

    gsettings set org.gnome.desktop.interface cursor-theme "Capitaine"
}
