#!/usr/bin/env bash

nxInstall() {
    nxPrint "Installing fonts..."

    sudo apt-get -qqy install fonts-noto fonts-roboto

    #fc-cache -fv

    gsettings set org.gnome.desktop.interface document-font-name "Roboto 10"
    gsettings set org.gnome.desktop.interface font-name "Noto Sans 10"
    gsettings set org.gnome.desktop.interface monospace-font-name "Ubuntu Mono 10"
    gsettings set org.gnome.desktop.wm.preferences titlebar-font "Noto Sans Bold 10"
}
