#!/usr/bin/env bash

nxConfig() {
    nxConfirm redshift "Install redshift?" yes
}

nxInstall() {
    if ! $(nxConfirm redshift); then
        return
    fi

    nxPrint "Installing redshift..."
    sudo apt-get -qqy install redshift

    mkdir -p ~/.config/autostart
    cp redshift.desktop ~/.config/autostart/

    echo | sudo tee --append /etc/geoclue/geoclue.conf
    cat geoclue.conf | sudo tee --append /etc/geoclue/geoclue.conf
}
