#!/usr/bin/env bash

nxInstall() {
    nxPrint "Configuring GNOME System Monitor..."

    local s="org.gnome.gnome-system-monitor"

    gsettings set $s cpu-stacked-area-chart true
    gsettings set $s current-tab resources
    gsettings set $s graph-update-internval 1000
    gsettings set $s update-internval 1000
}
