#!/usr/bin/env bash

nxInstall() {
    nxPrint "Configuring sysctl.conf..."

    echo | sudo tee --append /etc/sysctl.conf
    echo kernel.nmi_watchdog=0 | sudo tee --append /etc/sysctl.conf
    echo vm.dirty_writeback_centisecs=1500 | sudo tee --append /etc/sysctl.conf
}
