#!/usr/bin/env bash

nxInstall() {
    nxPrint "Installing dash-to-dock extension..."

    git clone -q https://github.com/micheleg/dash-to-dock.git /tmp/dash-to-dock

    cd /tmp/dash-to-dock

    make && make install

    gnome-shell-extension-tool -e dash-to-dock@micxgx.gmail.com

    local ext='/org/gnome/shell/extensions/dash-to-dock/'

    dconf write "${ext}background-color" "'#000000'"
    dconf write "${ext}background-opacity" 0.4
    dconf write "${ext}click-action" "'minimize'"
    dconf write "${ext}custom-background-color" true
    dconf write "${ext}custom-theme-customize-running-dots" true
    dconf write "${ext}custom-theme-running-dots" true
    dconf write "${ext}dock-position" "'BOTTOM'"
    dconf write "${ext}intellihide" false
    dconf write "${ext}opaque-background" true
    dconf write "${ext}shift-click-action" "'launch'"
    dconf write "${ext}show-apps-at-top" true

    (nohup gnome-shell --replace < /dev/null > /dev/null 2>&1 &)
}
