#!/usr/bin/env bash

nxInstall() {
    nxPrint "Installing Hide top bar extension..."

    cd ~/.local/share/gnome-shell/extensions/
    git clone https://github.com/mlutfy/hidetopbar.git hidetopbar@mathieu.bidon.ca
    cd hidetopbar@mathieu.bidon.ca
    make schemas

    gnome-shell-extension-tool -e hidetopbar@mathieu.bidon.ca

    local ext="/org/gnome/shell/extensions/ext/"

    dconf write "${ext}enable-intellihide" false
    dconf write "${ext}mouse-sensitive" true
    dconf write "${ext}pressure-threshold" 10

    (nohup gnome-shell --replace < /dev/null > /dev/null 2>&1 &)
}
